name: Build and Deploy Artifacts

on: [push]

jobs:
  build:
    runs-on: macos-latest
    name: MacOS -> Build

    steps:
    - name: Clone DiligentGraphics.github.io repository
      uses: actions/checkout@v3
      with:
        submodules: recursive

    - name: Set up build environment
      if:  success()
      uses: DiligentGraphics/github-action/setup-build-env@v1
      with:
        platform: Emscripten

    - name: Build artifacts
      if: success()
      working-directory: ${{github.workspace}}
      run: |
        python ./build_artifacts.py

    - name: Upload artifacts
      if: success()
      uses: actions/upload-artifact@v4
      with:
        name: WebPage-DiligentGraphics.github.io
        path: |
          ${{github.workspace}}/BuildArtifacts
        retention-days: 90

  deploy:
    needs: build
    runs-on: macos-latest
    name: MacOS -> Deploy

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Download artifacts
      uses: actions/download-artifact@v4
      with:
        name: WebPage-DiligentGraphics.github.io
        path: ./build 

    - name: Deploy to GitHub Pages
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git checkout --orphan gh-pages
        git rm -rf .
        cp -r build/* .
        git add .
        git commit -m "Deploy to GitHub Pages"
        git push -f origin gh-pages
